const { call, message } = require('../../utils/cloud')
const presets = [{ name: '不使用模板', title: '', desc: '' }, { name: '甜蜜饮品', title: '奶茶一杯', desc: '凭此礼物可以兑换一杯喜欢的饮品。' }, { name: '洗碗券', title: '洗碗券', desc: '凭此券可以让对方洗碗一次。' }, { name: '家务券', title: '家务券', desc: '凭此券可以让对方完成一次家务。' }, { name: '晚餐券', title: '晚餐券', desc: '凭此券可以邀请对方共进晚餐。' }]
Page({
  data: { title: '', desc: '', credit: 1, maxCredit: getApp().globalData.maxCredit, presetIndex: 0, presets, submitting: false,
    copy: { pageTitle: '\u51c6\u5907\u4e00\u4efd\u793c\u7269', hint: '\u628a\u60f3\u9001\u7ed9\u5bf9\u65b9\u7684\u60ca\u559c\uff0c\u653e\u8fdb\u4f60\u4eec\u7684\u793c\u7269\u67dc\u3002', preset: '\u5feb\u901f\u9009\u62e9', title: '\u793c\u7269\u540d\u79f0', detail: '\u793c\u7269\u8bf4\u660e', credit: '\u9700\u8981\u79ef\u5206', reset: '\u91cd\u7f6e', save: '\u4e0a\u67b6\u793c\u7269' }, titlePlaceholder: '\u4f8b\u5982\uff1a\u5976\u8336\u4e00\u676f', descPlaceholder: '\u5151\u6362\u540e\u53ef\u4ee5\u505a\u4ec0\u4e48' },
  onTitleInput(e) { this.setData({ title: e.detail.value }) }, onDescInput(e) { this.setData({ desc: e.detail.value }) }, onCreditInput(e) { this.setData({ credit: e.detail.value }) },
  onPresetChange(e) { const p = presets[e.detail.value]; this.setData({ presetIndex: Number(e.detail.value), title: p.title, desc: p.desc }) },
  async saveItem() { if (this.data.submitting) return; const { title, desc, credit } = this.data; if (!title.trim() || title.length > 12 || desc.length > 100 || Number(credit) <= 0) return message(new Error('请检查礼物内容和积分')); this.setData({ submitting: true }); try { const result = await call('addElement', { list: 'MarketList', title: title.trim(), desc: desc.trim(), credit: Number(credit) }); if (result.error) throw new Error(result.error); wx.showToast({ title: '上架成功', icon: 'success' }); setTimeout(() => wx.navigateBack(), 700) } catch (_) {} finally { this.setData({ submitting: false }) } },
  resetItem() { this.setData({ title: '', desc: '', credit: 1, presetIndex: 0 }) }
})
