const { call, message } = require('../../utils/cloud')
const presets = [{ name: '不使用模板', title: '', desc: '' }, { name: '早睡早起', title: '今晚早点休息', desc: '为彼此留出充足的休息时间。' }, { name: '整理房间', title: '一起整理房间', desc: '让我们的空间变得更舒适。' }, { name: '健康运动', title: '一起运动', desc: '保持健康，也保持陪伴。' }, { name: '准备晚餐', title: '准备一顿晚餐', desc: '一起享受一顿认真准备的晚餐。' }, { name: '小小惊喜', title: '准备一份小礼物', desc: '给对方一个温柔的惊喜。' }]
Page({
  data: { title: '', desc: '', credit: 1, maxCredit: getApp().globalData.maxCredit, presetIndex: 0, presets, submitting: false,
    copy: { pageTitle: '\u5199\u4e0b\u4e00\u4e2a\u5fc3\u613f', hint: '\u7ed9\u5bf9\u65b9\u4e00\u4e2a\u53ef\u4ee5\u88ab\u5b8c\u6210\u7684\u5c0f\u671f\u5f85\u3002', preset: '\u5feb\u901f\u9009\u62e9', title: '\u5fc3\u613f\u540d\u79f0', detail: '\u5fc3\u613f\u8be6\u60c5', credit: '\u5956\u52b1\u79ef\u5206', reset: '\u91cd\u7f6e', save: '\u4fdd\u5b58\u5fc3\u613f' }, titlePlaceholder: '\u4f8b\u5982\uff1a\u4e00\u8d77\u770b\u4e00\u573a\u7535\u5f71', descPlaceholder: '\u5199\u4e0b\u5177\u4f53\u8981\u505a\u4ec0\u4e48' },
  onTitleInput(e) { this.setData({ title: e.detail.value }) }, onDescInput(e) { this.setData({ desc: e.detail.value }) }, onCreditInput(e) { this.setData({ credit: e.detail.value }) },
  onPresetChange(e) { const p = presets[e.detail.value]; this.setData({ presetIndex: Number(e.detail.value), title: p.title, desc: p.desc }) },
  async handleTap() { if (this.data.submitting) return; const { title, desc, credit } = this.data; if (!title.trim() || title.length > 12 || desc.length > 100 || Number(credit) <= 0) return message(new Error('请检查心愿内容和积分')); this.setData({ submitting: true }); try { const result = await call('addElement', { list: 'MissionList', title: title.trim(), desc: desc.trim(), credit: Number(credit) }); if (result.error) throw new Error(result.error); wx.showToast({ title: '保存成功', icon: 'success' }); setTimeout(() => wx.navigateBack(), 700) } catch (_) {} finally { this.setData({ submitting: false }) } },
  resetMission() { this.setData({ title: '', desc: '', credit: 1, presetIndex: 0 }) }
})
