const { call, message, readableError } = require('../../utils/cloud')
Page({
  data: { search: '', credit: 0, user: '', allItems: [], unboughtItems: [], boughtItems: [], loading: true, hasSpace: false, errorText: '', l: { title: '\u7ed9\u5bf9\u65b9\u7684\u793c\u7269', points: '\u7684\u79ef\u5206', search: '\u641c\u7d22\u793c\u7269', loading: '\u6b63\u5728\u52a0\u8f7d\u793c\u7269\u2026', empty: '\u8fd8\u6ca1\u6709\u793c\u7269', available: '\u5f85\u5151\u6362', exchanged: '\u5df2\u5151\u6362', cost: '\u9700\u8981', point: '\u5206', exchange: '\u5151\u6362', delete: '\u5220\u9664', done: '\u5df2\u5151\u6362', noSpaceTitle: '\u8bf7\u5148\u521b\u5efa\u6216\u52a0\u5165\u53cc\u4eba\u7a7a\u95f4', noSpaceHint: '\u7a7a\u95f4\u8fde\u63a5\u540e\uff0c\u624d\u80fd\u4e0a\u67b6\u548c\u5151\u6362\u793c\u7269\u3002', goSpace: '\u53bb\u521b\u5efa\u7a7a\u95f4', errorTitle: '\u793c\u7269\u52a0\u8f7d\u5931\u8d25', retry: '\u91cd\u8bd5' } },
  async onShow() { this.setData({ loading: true, errorText: '' }); try { const space = await getApp().refreshSpace(); if (!space) return this.setData({ hasSpace: false }); const r = await call('getCurrentSpace'); const me = (r.members || []).find(x => x._openid === r.openId); this.setData({ hasSpace: true, credit: me ? me.credit : 0, user: me ? me.displayName : '' }); await this.load() } catch (err) { this.setData({ errorText: readableError(err, 'listElements') }) } finally { this.setData({ loading: false }) } },
  async load() { const r = await call('listElements', { list: 'MarketList' }); this.setData({ allItems: r.data || [] }); this.filterItem() }, retry() { this.onShow() }, openSpace() { wx.switchTab({ url: '../MainPage/index' }) },
  onSearch(e) { this.setData({ search: e.detail.value }); this.filterItem() }, filterItem() { const s = this.data.search.trim(); const a = s ? this.data.allItems.filter(x => (x.title || '').includes(s)) : this.data.allItems; this.setData({ unboughtItems: a.filter(x => x.available), boughtItems: a.filter(x => !x.available) }) },
  toDetailPage(e, pending) { const x = (pending ? this.data.unboughtItems : this.data.boughtItems)[e.currentTarget.dataset.index]; if (x) wx.navigateTo({ url: '../MarketDetail/index?id=' + x._id }) }, toDetailPageUpper(e) { this.toDetailPage(e, true) }, toDetailPageLower(e) { this.toDetailPage(e, false) }, toAddPage() { wx.navigateTo({ url: '../MarketAdd/index' }) },
  async buyItem(e) { const x = this.data.unboughtItems.find(v => v._id === e.currentTarget.dataset.id); if (!x) return; if (this.data.credit < x.credit) return message(new Error('\u79ef\u5206\u4e0d\u8db3')); const confirmed = await new Promise(resolve => wx.showModal({ title: '\u5151\u6362\u793c\u7269', content: `\u5c06\u6d88\u8017 ${x.credit} \u79ef\u5206\u5151\u6362\u300c${x.title}\u300d`, confirmColor: '#ff4e76', success: r => resolve(r.confirm) })); if (!confirmed) return; try { await call('purchaseItem', { id: x._id }); wx.showToast({ title: '\u5151\u6362\u6210\u529f', icon: 'success' }); await this.onShow() } catch (_) {} },
  async toggleStar(e) { const x = this.data.allItems.find(v => v._id === e.currentTarget.dataset.id); if (!x) return; try { await call('editStar', { _id: x._id, list: 'MarketList', value: !x.star }); await this.load() } catch (_) {} },
  async deleteItem(e) { const confirmed = await new Promise(resolve => wx.showModal({ title: '\u5220\u9664\u793c\u7269', content: '\u786e\u5b9a\u5220\u9664\u8fd9\u4efd\u793c\u7269\u5417\uff1f', success: r => resolve(r.confirm) })); if (!confirmed) return; try { await call('deleteElement', { _id: e.currentTarget.dataset.id, list: 'MarketList' }); await this.load() } catch (_) {} }
})
